
<!-- saved from url=(0109)ftp://ftp.gwdg.de/pub/linux/handhelds/distributions/familiar/releases/v0.8.4/install/bootblaster-continue.inc -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></head><body><p>Continue with one of these installation steps:</p>
    <ul>
        <li><a href="ftp://ftp.gwdg.de/pub/linux/handhelds/distributions/familiar/releases/v0.8.4/install/install-serial.html">Install via serial port</a>
        </li><li><a href="ftp://ftp.gwdg.de/pub/linux/handhelds/distributions/familiar/releases/v0.8.4/install/install-cf.html">Install via Compact Flash sleeve</a>
    </li></ul>
<p></p>
</body></html>